/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jadamantine;

import org.junit.Test;

import static org.junit.Assert.*;

public class LibraryTest {
   /* @Test public void testSomeLibraryMethod() {
        Compiler classUnderTest = new Compiler();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }*/
}
